#Routing policy
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
        filters:
        - AuthenticationFilter
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet
        filters:
        - AuthenticationFilter
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/**
        filters:
        - AuthenticationFilter
  application:
    name: CLOUD-API-GATEWAY
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 2222
